table <nope> {0.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 255.255.255.255/32, 240.0.0.0/4}
table <private> {127.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12, 10.0.0.0/8 }
table <dnsIPs> {127.0.0.1, 9.9.9.9, 1.1.1.1, 149.112.112.112}

# Options
set block-policy drop
set fingerprints "/etc/pf.os"
set ruleset-optimization basic
set skip on lo0
# Normalization
# Scrub incoming packets
scrub in all no-df
antispoof log quick for { lo en utun netboot egress ingress awd llw ap bridge anpi gif stf  }
block in from no-route to any
block in from urpf-failed to any
block drop in quick from <nope> to any
block drop out quick from any to <nope>
# Default deny policy
block in all
#Allow in dhcp
pass in quick inet proto udp from <private> port 67 to any port 68
#Allow Timemachine and printers - this can be disabled if you dont use either.
pass in quick proto udp to any port 5353
#Allow only Trusted DNS and NTP servers
pass out log quick proto { udp, tcp } to { <dnsIPs> } port { 53, 853 }
#Block all other DNS and NTP Servers
block out quick proto { udp, tcp } to any port { 53, 853 }
#Allow other traffic out
pass out
#Deny all just in case
block in
